name: Sync Fork with Upstream

on:
  schedule:
    # প্রতি ৫ মিনিটে একবার স্বয়ংক্রিয়ভাবে রান হবে
    - cron: '*/5 * * * *'
  workflow_dispatch: # Actions ট্যাব থেকে ম্যানুয়াল রান করার জন্য

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with Upstream
        run: |
          git remote add upstream https://github.com/drmlive/fancode-live-events.git
          git fetch upstream
          git checkout main
          git merge upstream/main -m "Sync with upstream repository"
          git push origin main
